---
name: container
on: [ push ]

jobs:

  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: docker 
      run: docker build --file Dockerfile --tag ${{ github.REPOSITORY }}:${{ github.SHA }} .
    - name: push the image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        tag: ${{ github.SHA }}
        image: ${{ github.REPOSITORY }}
        registry: ghcr.io
        username: ${{ github.ACTOR }}
        password: ${{ secrets.PUSHTOKEN }} 

  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1 
    - name: print commit sha
      run: echo ${{ github.sha }}
    - name: push the image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        tag: ${{ github.GITHUB_REF }}
        image: ${{ github.REPOSITORY }}
        registry: ghcr.io
        username: ${{ github.ACTOR }}
        password: ${{ secrets.PUSHTOKEN }}

  publish-latest:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1 
    - name: print commit sha
      run: echo ${{ github.sha }}
    - name: push the image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        tag: lastest
        image: ${{ github.REPOSITORY }}
        registry: ghcr.io
        username: ${{ github.ACTOR }}
        password: ${{ secrets.PUSHTOKEN }} 
