name: tests
on: [push]

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: go test
        run: go test .

  go-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: go build
        run: go build -o ./elastic-cluster-diff -ldflags "-X main.GitCommit=${{ github.sha }}" .
      - name: run executable
        run: ./elastic-cluster-diff --help
      - name: run executable
        run: ./elastic-cluster-diff --version
